language: haxe

os:
  - linux

haxe:
  - "4.0.1"
  - stable
  
matrix:
  allow_failures:
    - haxe: development

install:
  #- haxelib install travix
  # to always use the latest version of travix comment out the previous line and uncomment the next
  # - haxelib git travix https://github.com/back2dos/travix && pushd . && cd $(haxelib config)travix/git && haxe build-neko.hxml && popd
  # - haxelib run travix install

hxml:
  - html5.hxml
  - test.hxml
