name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: krdlab/setup-haxe@3437f1adfca98b22815d926271cc39faaf996f25 # v1.5.1
        with:
          haxe-version: 4.3.1
          cache-dependency-path: 'travis.hxml'
      - name: install
        run: |
          haxe -version
          haxelib install travis.hxml --always
          haxelib list
      - name: test
        run: |
          haxe -version
          haxe travis.hxml
          ls
      - name: build_runable
        run: haxe html5.hxml
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: html5
          path: buld/html5